# 使用说明 V4.4.0
# 1. 使用docker-compose  宿主机不需要配置host来发现
# 2. 无需修改源码，根目录  docker-compose up 即可
# 3. 静静等待服务启动

version: '3'
services:
  encryptor-boot:
    build:
      context: ./
    restart: always
    image: harbor.fulltruck.net/demo/encryptor-boot
    container_name: encryptor-boot
    ports:
      - 8081:8081
