version: '3'
services:
  encryptor-boot:
    build:
      context: ./
    restart: always
    image: harbor.fulltruck.net/demo/encryptor-boot
    container_name: encryptor-boot
    ports:
      - 8081:8081
