version: '3'
services:
  hello_encryptor:
    build:
      context: ./
    restart: always
    image: ${REGISTRY}/${NAMESPACE}/hello-encryptor:${TAG}
    container_name: hello-encryptor
    ports:
      - 8081:8081
