server:
  port: 8081
  servlet:
    context-path: /

jasypt:
  encryptor:
    password: WTt2x8ruSGE8ZSA7
    property:
      prefix: AWR(
      suffix: )

spring:
  datasource:
    url: AWR(U1bDWi/w7FNzreHyS1sDKm0Guz8WO5Ri8g3RU/oeB+w4cMRJzpCdX/+v6v3jPSl/TvO8vTqn/jrh/CW2d1fgl7kPJQr2cCBZ35IPU0qTnKADjVIj5BaqxlGLDwD2KOyOSzZdeW7MsCqn/K6gL1n6bPAf3ZquVzeqO+82+rYsvmstPOwCYkuKSebZjXD1/XMqcjIDguAbeiX/baK7ssJ0t/IX/xk9eBFK3HL4LStgyDOXMkHf/z0HNFp8NSMPlBxC4Ynvw3JFH4TSZ0uw+ttWRA==)
    username: AWR(0zaD1+eskQVHqCHscVhtMHINbMhwlu1lCW+uNlqMqIW/mOSgogm749bG9KQIDqxe)
    password: AWR(26zrct9KYQPBZLP8kFfyr3s6tLC95aPjtWeZHNxvrtW9clDIuLgftcbXng0ZuhVO)
