server:
  port: 8081
  servlet:
    context-path: /

jasypt:
  encryptor:
    password: encryptor@2023
    property:
      prefix: ENC(
      suffix: )

spring:
  datasource:
    url: ENC(Dyx/12qjdzBUyTsDGpvpNgUzxqqU7RuHGa/uaaS5FGFcBrEJYnAJSZqWM3UwXVs/BCI8jU50iimuXIV+LrWKju1fZjvDfmta2gMfC+C0whRKvKZd3oNkLMvorMbiNl1nj2UaE9fuORAaZqMyMxf5yQCljon6hvE9HeVjafJapD7wQIvWi2TgFOq3sDduDRuM62UceyIej+aOuD1Xx1SbBdwTPOAttw/rurGv1mo+bjertoC5ftTTNRjwL6XAI4qleXV6E77PEkUVyM5uZDaWxA==)
    username: ENC(ICmlVs1gm3KOt6sz7BWS/A8+Gr+KwyWi6jpf2Fm4kirouWt3Og4sUUixWQP50GNq)
    password: ENC(2hR06WKc7YSXKhFXaK0jUetzsGuagP4vFLJgMQn/g173j5anS1K8gTsBdaGI0IyK)
